# fly.toml app configuration file generated for rails-api-nextjs-verification-app-back on 2023-11-23T00:09:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rails-api-nextjs-verification-app-back"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
